apiVersion: v1
kind: Service
metadata:
  name: {{ template "base.fullname" $ }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "base.labels" $ | nindent 4 }}
spec:
  type: {{ .Values.serviceType }}
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{ template "base.fullname" $ }}
  sessionAffinity: ClientIP
